// <auto-generated />
namespace PMF_Movie_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddRental : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRental));
        
        string IMigrationMetadata.Id
        {
            get { return "201907150816205_AddRental"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
